name: Build Management

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm ci
      - name: Build packages
        run: npm run build

  pre_release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Publish Preview Version
        run: npm run ci:prerelease
        env:
          BUILD_BUILDID: ${{ github.run_number }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Prepublish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          preRelease: true
          dependencies: false
          packagePath: ./packages/vscode-codegen/
          registryUrl: https://open-vsx.org
      - name: Prepublish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCODE_TOKEN }}
          preRelease: true
          dependencies: false
          packagePath: ./packages/vscode-codegen/
          registryUrl: https://marketplace.visualstudio.com

  release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Set up git
        run: |
          git config --global user.email "mail@florian-rappl.de"
          git config --global user.name "Florian Rappl"
      - name: Update Release Date
        run: npm run ci:version-update
      - name: Publish Release Version
        run: npm run ci:release
        env:
          BUILD_BUILDID: ${{ github.run_number }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          dependencies: false
          packagePath: ./packages/vscode-codegen/
          registryUrl: https://open-vsx.org
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCODE_TOKEN }}
          dependencies: false
          packagePath: ./packages/vscode-codegen/
          registryUrl: https://marketplace.visualstudio.com
